queue:
  backend: "sqlite"           # "sqlite" (padrão) | "redis"
  sqlite:
    path: ".runtime/janus_queue.db"
  redis:
    url_env: "REDIS_URL"      # ex.: redis://localhost:6379/0
  max_attempts: 5
  tick_batch: 50              # máximo de jobs por tick
  backoff_seconds_cap: 60     # teto do backoff exponencial

locks:
  backend: "file"             # "file" (padrão) | "redis"
  redis:
    url_env: "REDIS_URL"
  ttl_seconds: 15

rate_limits:
  base-testnet:
    rps: 10                   # requisições/processos por segundo
    burst: 20
  solana-testnet:
    rps: 8
    burst: 16

backpressure:
  high_watermark_inflight: 200
  resume_threshold: 120

tracing:
  enabled: true
  exporter: "otlp"            # "otlp" | "none"
  otlp_endpoint_env: "OTEL_EXPORTER_OTLP_ENDPOINT"  # ex.: http://localhost:4317
  service_name: "janus-node"

