name: contracts
on:
  push:
    paths:
      - "contracts/**"
      - ".github/workflows/contracts.yml"
  pull_request:
    paths:
      - "contracts/**"
jobs:
  contracts-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Build & Test (stub)
        run: echo "TODO: forge build && forge test"
