name: docs
on:
  push:
    paths:
      - "apps/docs/**"
      - ".github/workflows/docs.yml"
  pull_request:
    paths:
      - "apps/docs/**"
jobs:
  docs-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install deps
        run: pnpm i
      - name: Build docs (stub)
        run: echo "TODO: docusaurus build"
