name: gateway
on:
  push:
    paths:
      - "apps/gateway/**"
      - "packages/adapters/base-solana/**"
      - ".github/workflows/gateway.yml"
  pull_request:
    paths:
      - "apps/gateway/**"
      - "packages/adapters/base-solana/**"
jobs:
  gateway-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install deps
        run: pnpm i
      - name: Build adapter
        run: pnpm --filter @janus/adapter-base-solana build
      - name: Build gateway
        run: pnpm --filter @janus/gateway build
