name: images
on:
  push:
    branches: [ main ]
    paths:
      - "apps/gateway/**"
      - "packages/adapters/base-solana/**"
      - ".github/workflows/images.yml"

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push gateway
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ops/docker/gateway.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/janus-gateway:latest
      - name: Build & push adapter
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ops/docker/adapter.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/janus-adapter:latest
