name: publish-images-testnet
on:
  release:
    types: [prereleased]

jobs:
  push:
    runs-on: ubuntu-latest
    permissions: { packages: write, contents: read }
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - name: Build & push gateway (testnet)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ops/docker/gateway.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/janus-gateway:${{ github.event.release.tag_name }}
      - name: Build & push adapter (testnet)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ops/docker/adapter.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/janus-adapter:${{ github.event.release.tag_name }}
