name: publish-images
on:
  release:
    types: [published]

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - name: Build & push gateway
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ops/docker/gateway.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/janus-gateway:${{ github.ref_name }}
      - name: Build & push adapter
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ops/docker/adapter.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/janus-adapter:${{ github.ref_name }}
