name: release-testnet
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "apps/**"
      - "packages/**"
      - "contracts/**"
      - ".github/workflows/release-testnet.yml"

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with: { node-version: 20 }
      - name: Install tools
        run: npm i -g standard-version pnpm
      - name: Install deps
        run: pnpm i
      - name: Bump pre-release (testnet)
        run: |
          standard-version --prerelease testnet --release-as patch --skip.commit=true --skip.tag=true
          VERSION=$(node -p "require('./package.json').version")-testnet
          echo "REL_TAG=v${VERSION}" >> $GITHUB_ENV
      - name: Create GitHub pre-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.REL_TAG }}
          prerelease: true
          name: "Testnet ${{ env.REL_TAG }}"
          body: "Automated testnet pre-release. No mainnet deploy."
