name: verify-contracts
on:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: foundry-rs/foundry-toolchain@v1
        with: { version: nightly }
      - name: Verify on BaseScan
        env:
          EXECUTOR_ADDR: ${{ secrets.EXECUTOR_ADDR }}
          REGISTRY_ADDR: ${{ secrets.REGISTRY_ADDR }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          RPC_URL_BASE_MAINNET: ${{ secrets.RPC_URL_BASE_MAINNET }}
        run: |
          forge verify-contract $EXECUTOR_ADDR contracts/src/Executor.sol:Executor --etherscan-api-key $ETHERSCAN_API_KEY --chain-id 8453
          forge verify-contract $REGISTRY_ADDR contracts/src/Registry.sol:Registry --etherscan-api-key $ETHERSCAN_API_KEY --chain-id 8453
